### ISSUE TITLE
Deploy Solr to dev env

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-infrastructure#115]
We need a formal deployment for the Solr, https://solr.apache.org/ , currently, we deployed a temporary instance of solar (by a docker container) to dev env, but we need a formal deployment for it, maybe a cluster structure as mentioned in the official document: https://solr.apache.org/operator/resources.html#tutorials

And also, we need to consider how to store the data, the Solr need to save the index file on disk, but please make sure every re-deployment and upgrade of the solr would not lose the data on disk, maybe some storage voluemn on disk?

**Comment by dadiorchen** [comment]
@emmanue can you look at this?

**Comment by emmanue** [comment]
Yes @dadiorchen I'm on it.

**Comment by dadiorchen** [comment]
@emmanue  you are my hero1

**Comment by sebastiangaertner** [comment]
@emmanue dito!
