### ISSUE TITLE
Set up domain: https://beta-map.treetracker.org/

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-infrastructure#116]
We need to set up the domain: https://beta.map.treetracker.org/ and point to service: https://prod-k8s.treetracker.org/web-map-beta/demo

**Comment by sebastiangaertner** [comment]
We are actually going to use map.greenstand.org

**Comment by dadiorchen** [comment]
So the beta goes to map.greenstand.org? 
And how about current map.treetracker.org?

**Comment by sebastiangaertner** [comment]
We will leave map.treetracker.org running for a couple of months and promote the new URL. Then we will just set a forwarder. Does that sound right?
