### ISSUE TITLE
Fix our secondary database backup by simplebackups

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-infrastructure#136]
we are using https://simplebackups.com/postgresql-backup/ to backup our DB, now it's failing, please help us solve the problem.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5744708/213335872-6d48400e-77ce-4810-a0a0-06b36735eb1f.png">

you can manually resolve the permissions for the readonlyuser, so the backup can run.  Having the secondary backup offline is top level risk for the entire platform.

**Comment by emmanue** [comment]
Fixed. Thanks to @ZavenArra  and @dadiorchen  for your guidance and support.

**Comment by emmanue** [comment]
We were able to solve the issue with the herbarium schema.
