### ISSUE TITLE
Scale the experiment-1 cluster by adding more nodes or upgrading existing node with higher CPU capacity

### ISSUE THREAD

**Issue by mahdi1ba** [Greenstand/treetracker-infrastructure#187]
We Faced a problem of insufficient CPU when installing knative in the experiment-1 cluster. 

So could you please adding more nodes to the experiment-1 cluster or upgrading the existing node with higher CPU capacity.

Thank you

**Comment by dadiorchen** [comment]
@mahdi1ba is this okay now?

**Comment by mahdi1ba** [comment]
@dadiorchen Yes It's okay now .Thank you
