### ISSUE TITLE
Make sure the prod k8s's resource is enough

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-infrastructure#189]
It seems the mem is high in some nodes:

<img width="1200" alt="image" src="https://github.com/Greenstand/treetracker-infrastructure/assets/5744708/9a429481-7788-4bf8-8a9a-853a5c6776d9">

**Comment by dadiorchen** [comment]
Maybe this cause #188

**Comment by emmanue** [comment]
Done.
