### ISSUE TITLE
The generated password by terraform can not be shown on digitalocean panel

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-infrastructure#202]
<img width="1182" alt="image" src="https://github.com/Greenstand/treetracker-infrastructure/assets/5744708/e66c38b7-e3de-4bf7-a862-78834992c784">

We need to find a good practice on handling password in terraform.

**Comment by emmanue** [comment]
![image](https://github.com/Greenstand/treetracker-infrastructure/assets/20098437/b6944ecb-eb61-4357-84b8-838ed76cfa78)
The password is set. It has to do with password generation.

**Comment by emmanue** [comment]
Done.
