### ISSUE TITLE
Customize the user profile pages to fit Greenstand style and brand

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-infrastructure#206]
<img width="1440" alt="image" src="https://github.com/Greenstand/treetracker-infrastructure/assets/5744708/a299a5a0-1d39-4987-8f5f-a6966a9f1b3e">

you can access this page here: https://dev-k8s.treetracker.org/raw-client/

As we do on the `login` page, we can also customize these page above, we way to do it is attach `html` and `css` to current theme folder of keycloak docker image, as shown in this PR https://github.com/Greenstand/treetracker-infrastructure/pull/203

this is our customized page for login:
<img width="965" alt="image" src="https://github.com/Greenstand/treetracker-infrastructure/assets/5744708/b6b8f283-a76c-4e48-8761-cb94dfe176cd">

**Comment by Mohmn** [comment]
@dadiorchen i got the keyclock docker image runing on my local

![Screenshot from 2023-11-25 02-33-53](https://github.com/Greenstand/treetracker-infrastructure/assets/37132584/b68b85ae-39b6-425c-83f2-22c59bf0fe8e)

is there any mock avalble for user profile page

**Comment by dadiorchen** [comment]
@Mohmn mock? do you mean UX/UI design? No, it isn't easy to get designer involved, because we are not going to create a totally new UI, we just adjust the current page/css to fit our style/color, and also as first step, it is not important to give a perfect UI, just go through the things and make the replacement happen is good enough, we can improve the ui later.

**Comment by dadiorchen** [comment]
BTW, nice job!

**Comment by Mohmn** [comment]
> @Mohmn mock? do you mean UX/UI design? No, it isn't easy to get designer involved, because we are not going to create a totally new UI, we just adjust the current page/css to fit our style/color, and also as first step, it is not important to give a perfect UI, just go through the things and make the replacement happen is good enough, we can improve the ui later.

Got it , will add the necessary styling
