### ISSUE TITLE
Make webmap config a template file, whose host is updated on copy

### ISSUE THREAD

**Issue by mckornfield** [Greenstand/treetracker-infrastructure#4]
To make it easier to deploy, we should have a template file for the webmap config... it might be worth doing this for the other configs as well so they can be committed without passwords

**Comment by deepwinter** [comment]
there's an example file in each repo.. but the problem with actually using the correctly named file is that when devs copy the true values in, that file will be tracked and accidentally committed.

we could implement a strategy where the code looks first in our deployment spot for the file, which could be committed as empty, and then after that in the dev spot.   i'm still wary that this will lead to passwords in the repo accidentally though.

**Comment by mckornfield** [comment]
I think the right strategy is to put the files in with template values missing, including:
ip addresses
hostnames
usernames
passwords

These will be filled in at deploy time. The proper way to do so from what I understand is vault https://docs.ansible.com/ansible/latest/user_guide/vault.html

**Comment by deepwinter** [comment]
but regarding what i mentioned above about devs accidentally committing their real config file, we would still call the committed template something different from config.js, right?

**Comment by mckornfield** [comment]
Yes definitely. I call the web map one "web-map-config.js", but we can change the name of all of the files. They also will be committed as templates to the infrastructure repo and not the normal repos

**Comment by deepwinter** [comment]
Ah I see, I was misunderstanding where you were suggesting the templating would take place. That makes total sense.

**Comment by mckornfield** [comment]
Done by f91ecee2fb30f3af472e5306c9358577355c7b92
