### ISSUE TITLE
Use Terraform to deploy s3 bucket backed partial staging of web map application

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-infrastructure#50]
Create terraform to provision an s3 bucket as a static website for the purposes of deploying a staged version of the web map against the production database.

This can follow a similar resource plan to the module we currently use for deploying static web applications, but should not deploy a CDN.

**Comment by vinodhinivijayan** [comment]
I have started working on it .Can you share access key and secret key
