### ISSUE TITLE
Build and deploy the new web map site project to dev env.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-infrastructure#56]
* Because we switched to next.js, the build and deployment would change, previously, we are single page app, and using creat-react-app, so it's about building with CRA and deploy to CDN (static files), now we need build with next.js, and need to deploy to I guess node.js server to handle page rendering. 
* We need to do it in this branch `web-map-site` rather than `master`.
* Please ask in the slack channel if you need special permission.
* Reference: https://github.com/Greenstand/treetracker-web-map-client/tree/web-map-site/.github/workflows
* Prerequisites: Greenstand/treetracker-web-map-client#117 
---
Some hints:
* Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
* Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
* To know more about our organization, visit our [website](https://greenstand.org).

**Comment by ZavenArra** [comment]
how is this going?

**Comment by jwgatt** [comment]
Can someone else take this? I'm a little busy with a PR from this repo.

**Comment by dadiorchen** [comment]
@ximena9201 are you on this? deploy the new web map client?
