### ISSUE TITLE
Analyze mobile-api errors found on old prod droplet

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-infrastructure#6]
[treetraccker-mobile.api.log](https://github.com/Greenstand/treetracker-infrastructure/files/3192744/treetraccker-mobile.api.log)

**Comment by mckornfield** [comment]
There appear to be two recurring issues in the logs:
UnhandledPromiseRejectionWarning: error: remaining connection slots are reserved for non-replication superuser connections
And
Can't set headers after they are sent.

**Comment by deepwinter** [comment]
Is that first one still showing?  It's caused by the cluster rebuilder taking too long, and piling up on itself, using up all the postgres connections in the pool.  I slowed down the the cron on that last week, which should hold us for a bit until we can implement a more segmented caching strategy.

**Comment by deepwinter** [comment]
The 2nd one is probably a minor api coding error - would you mind filing that against the api repo that it's coming from?

**Comment by mckornfield** [comment]
I will file an issue sure. I can check later to see if it's still happening (1 that is)

**Comment by mckornfield** [comment]
Closing this issue here, and created another issue in the appropriate repo
