### ISSUE TITLE
Sealed secrets not creating secrets

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-infrastructure#90]
k8s was recently updated by DO to version 1.21.11, and now we are seeing a sealed secret (for the reporting API) not unsealing into a secret.   I checked and the sealed secrets controller github has a release at v0.17.5, but our infra repo shows that we deployed from v0.13.1 - I think the problem is probably that our controller is out of date.  

 Should we just run '`kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.5/controller.yaml`?  My main concern would be some effect this could have on any of our existing secrets or sealed secrets.

**Comment by TANguyen1893** [comment]
Caused by this https://github.com/bitnami-labs/sealed-secrets/issues/822. Deployment objects were manually updated to use the image from dockerhub. We might have to upgrade since it's possible they won't update charts to include the dockerhub image.

**Comment by ZavenArra** [comment]
The original problem was resolved by locating a version of the docker image for the currently installed sealed secrets controller, and updating the deploying to use this version.

We should upgrade to v0.17.5 to start using the new bitnami docker repository.  This should be tested in dev and test envs before being upgraded in production.
